#include "codegen/metadata.h"

const std::vector<MetadataAbstract> metadataVec = {
    // Integer
    MetadataInteger("stageWidth", 600),
    MetadataInteger("stageHeight", 500),
    MetadataInteger("roomSize", 4, 1, 8),
    MetadataInteger("lives", 3),
    MetadataInteger("maxAbilityLevel", 2, 0, 2),
    MetadataInteger("bornDuration", 300),
    MetadataInteger("bornLockDuration", 100),
    MetadataInteger("minPlayers", 1, 1, 8),
    // Boolean
    MetadataBool("supportSignin", true),
    MetadataBool("mustLogin", true),
    MetadataBool("allowGuest", true),
    MetadataBool("supportMsgServer", true),
    MetadataBool("runGame", true),
    MetadataBool("campOpSkydow", true),
    MetadataBool("campOpRoyal", true),
    MetadataBool("campOpThird", true),
    MetadataBool("setInitFocus", false),
    MetadataBool("setBornDuration", false),
    MetadataBool("nextGameEnabled", true),
    MetadataBool("playDefaultMusic", true),
    MetadataBool("disableNextGameOnMissionComplete", false),
    MetadataBool("useDefaultItems", false),
    MetadataBool("defCarryItems", false),
    MetadataBool("useDefaultCampLocs", false),
    MetadataBool("useCustomWeapons", false),
    MetadataBool("useCustomFarWeapons", false),
    MetadataBool("useCustomItems", false),
    MetadataBool("allowGuest", true),
    // String
    MetadataString("schema", "", true),
    MetadataString("title", "", true),
    MetadataString("map", "", true),
    MetadataString("stageBackgroundColor", "#999999"),
    MetadataString("gamezoneCode", "mission"),
    // Enum
    MetadataEnum("roomType", "close", {"close", "open"}),
    MetadataEnum("stageAlignHorizontal", "center", {"left", "center", "right"}),
    MetadataEnum("stageAlignVertical", "middle", {"top", "middle", "bottom"}),
    MetadataEnum("cameraAfterOver", "free", {"free", "restrict", "none"}),
    MetadataEnum("stageResolutionPolicy", "showAll",
                 {"showAll", "exactFit", "noBorder", "fixedWidth",
                  "fixedHeight", "origin"}),
    MetadataEnum("gameStartFadein", "fadein",
                 {"fadein", "fadeinL", "dark", "show"}),
    // List
    MetadataList<Point>("skydowLocs"),
    MetadataList<Point>("royalLocs"),
    MetadataList<Point>("thirdLocs"),
    MetadataList<Point>("initFocus"),
    MetadataList<std::string>("preloadSources"),
    MetadataList<std::string>("preloadResourcesExclude"),
    MetadataList<std::string>("carryItemCodes"),
    MetadataList<std::string>("releaseCamp", {"third", "royal", "skydow"},
                              {"third", "royal", "skydow", "random"}),
    MetadataList<std::string>("debugCamp", {"third", "royal", "skydow"},
                              {"third", "royal", "skydow", "random"}),
    // Unsupport
    MetadataUnsupport("customWeapons", ""),
    MetadataUnsupport("customFarWeapons", ""),
    MetadataUnsupport("customItems", ""),
};